#!/usr/bin/env bash
#
# Turns VERSION — the single source of truth — into the two forms the build
# needs: a Swift constant and a value for Info.plist.
#
# It exists because the version was hand-maintained in Info.plist and drifted:
# v0.1.1 and v0.2.0 both shipped announcing themselves as 0.1.0. Anything the
# build can derive, the build should derive.
#
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="$(tr -d ' \t\n' < VERSION)"
[ -n "$VERSION" ] || { echo "VERSION is empty" >&2; exit 1; }

mkdir -p build/generated
printf '%s\n' \
    "// Generated by Tools/generate-version.sh. Do not edit, do not commit." \
    "enum NoLidVersion {" \
    "    static let current = \"$VERSION\"" \
    "}" \
    > build/generated/Version.swift

printf '%s' "$VERSION"
